name: tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-node@v4
      with:
        node-version: 12.x
        cache: yarn
    - run: yarn --frozen-lockfile
    - run: yarn lint -- --max-warnings=0
    - run: yarn test -- --coverage
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/clover.xml
        flags: unittest
        fail_ci_if_error: true
